<template><main class="admin-page"><el-card><template #header><div class="header"><div><h1>管理端数据Dashboard</h1><span>平台运行与风险概览</span></div><el-button @click="router.push('/dashboard')">返回首页</el-button></div></template><div class="filters"><el-radio-group v-model="range" @change="changeRange"><el-radio-button label="today">今日</el-radio-button><el-radio-button label="7d">近7天</el-radio-button><el-radio-button label="30d">近30天</el-radio-button><el-radio-button label="custom">自定义</el-radio-button></el-radio-group><el-date-picker v-if="range==='custom'" v-model="customDates" type="daterange" value-format="YYYY-MM-DD" range-separator="至" start-placeholder="开始日期" end-placeholder="结束日期" @change="load" /></div><el-alert v-if="error" :title="error" type="error" :closable="false" /><el-row :gutter="16" class="metrics"><el-col v-for="item in metricItems" :key="item.label" :xs="12" :sm="6"><el-statistic :title="item.label" :value="item.value" /></el-col></el-row><el-divider /><el-row :gutter="24"><el-col :xs="24" :md="12"><h2>风险等级统计</h2><div ref="riskChart" class="chart"></div></el-col><el-col :xs="24" :md="12"><h2>画像分布统计</h2><div ref="profileChart" class="chart"></div></el-col><el-col :xs="24"><h2>风险趋势</h2><div ref="trendChart" class="chart trend"></div></el-col></el-row></el-card></main></template>
<script setup lang="ts">
import { nextTick, onMounted, ref } from 'vue'; import { useRouter } from 'vue-router'; import { ElMessage } from 'element-plus'; import * as echarts from 'echarts'; import { getOverview, getFraudStatistics, getProfileStatistics, getFraudTrend } from '../api/admin';
const router = useRouter(); const error = ref(''); const overview = ref<any>({}); const riskChart = ref<HTMLElement>(); const profileChart = ref<HTMLElement>(); const trendChart = ref<HTMLElement>(); const range = ref('30d'); const customDates = ref<string[]>([]);
const metricItems = [{ label: '用户数量', get value() { return overview.value.userCount || 0; } }, { label: 'AI咨询次数', get value() { return overview.value.chatCount || 0; } }, { label: '诈骗检测次数', get value() { return overview.value.fraudCount || 0; } }, { label: '高风险事件', get value() { return overview.value.highRiskCount || 0; } }];
function params() { const today = new Date(); const end = today.toISOString().slice(0, 10); if (range.value === 'custom' && customDates.value.length === 2) return { startDate: customDates.value[0], endDate: customDates.value[1] }; const days = range.value === 'today' ? 0 : range.value === '7d' ? 6 : 29; const startDate = new Date(today.getTime() - days * 86400000).toISOString().slice(0, 10); return { startDate, endDate: end }; }
function renderCharts(risk: any, profile: any, trend: any[]) { if (riskChart.value) echarts.init(riskChart.value).setOption({ tooltip: {}, xAxis: { type: 'category', data: Object.keys(risk.levels || {}) }, yAxis: { type: 'value' }, series: [{ type: 'bar', data: Object.values(risk.levels || {}), itemStyle: { color: '#e67e22' } }] }); if (profileChart.value) echarts.init(profileChart.value).setOption({ tooltip: {}, series: [{ type: 'pie', radius: ['35%', '65%'], data: Object.entries(profile.riskPreferences || {}).map(([name, value]) => ({ name, value })) }] }); if (trendChart.value) echarts.init(trendChart.value).setOption({ tooltip: { trigger: 'axis' }, legend: { data: ['检测数量', '高风险数量'] }, xAxis: { type: 'category', data: trend.map(item => item.date) }, yAxis: { type: 'value' }, series: [{ name: '检测数量', type: 'line', data: trend.map(item => item.total), smooth: true }, { name: '高风险数量', type: 'line', data: trend.map(item => item.highRisk), smooth: true }] }); }
async function load() { try { const query = params(); const [o, r, p, t]: any[] = await Promise.all([getOverview(query), getFraudStatistics(), getProfileStatistics(), getFraudTrend(query)]); overview.value = o.data.data; await nextTick(); renderCharts(r.data.data, p.data.data, t.data.data || []); } catch { error.value = '暂无管理数据或当前账号没有管理员权限'; ElMessage.error(error.value); } }
function changeRange() { if (range.value !== 'custom') load(); }
onMounted(load);
</script>
<style scoped>.admin-page{min-height:100vh;background:#f4f7fb;padding:24px}.header{display:flex;justify-content:space-between;align-items:center}h1{font-size:28px;margin:0 0 6px;color:#1769aa}.header span{font-size:18px;color:#6b7280}.filters{display:flex;gap:12px;align-items:center;flex-wrap:wrap;margin-bottom:20px}.metrics{margin:12px 0 24px}.chart{height:300px}.trend{height:340px}h2{font-size:20px}@media(max-width:600px){.admin-page{padding:8px}.header{align-items:flex-start}.header h1{font-size:23px}}</style>
